//TILES RELATED
const double TILE_SIZE = 128;
const int GENERAL_WIDTH = 9;
const int GENERAL_HEIGHT = 5;
const double SCREEN_WIDTH = 1280;
const double SCREEN_HEIGHT = 768;
//COMPUTER RELATED
const int DEFAULT_COMPUTER_HP = 300;
const int TEST_DUMMY_HP = 4500;
//RECHARGE
const double FAST_RECHARGE = 7.5;
const double SLOW_RECHARGE = 30.0;
const double VERY_SLOW_RECHARGE = 50.0;
//PROJECTILES AND EXPLOSION
const int BASIC_BULLET_DAMAGE = 35;
const double BASIC_BULLET_SPEED = 500;
const int EXPLOSION_DAMAGE = 1800;
//CURRENCY RELATED
const double DEFAULT_TIMEOUT = 7.5;
const int DEFAULT_COMPUTER_EARNING = 50;
//VIRUS RELATED
const int BASIC_BOT_HEALTH = 300;
const double BASIC_BOT_SPEED = 35;
const double BASIC_BOT_HIT_COOLDOWN = 0.05;
const int BASIC_VIRUS_DAMAGE = 50;
const int SPEED_BOT_HEALTH = 300;
const int LIGHT_ARMORED_BOT_HEALTH = 600;
const int ARMORED_BOT_HEALTH = 1300;
const double SPEED_BOT_SPEED = 125;
const double SPEED_BOT_HIT_COOLDOWN = 0.015;
//TRAY CONFIG
const int MAX_DEFENDERS_COUNT = 4;
