// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADB2EpWBt5cxkfjsdiEOZn9rur-4uPvNw',
    appId: '1:514661727749:web:aa8f72c967963d8996a66c',
    messagingSenderId: '514661727749',
    projectId: 'mainframe-warfare',
    authDomain: 'mainframe-warfare.firebaseapp.com',
    storageBucket: 'mainframe-warfare.appspot.com',
    measurementId: 'G-RJ1XK8Y26W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Y_eNrGOZCxlUMXDxZ_y04n4JX5Fd55Q',
    appId: '1:514661727749:android:97b0cf07bc88aac096a66c',
    messagingSenderId: '514661727749',
    projectId: 'mainframe-warfare',
    storageBucket: 'mainframe-warfare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7QcQtHacfflLRNQGxFVSu4LPtnfmrkB0',
    appId: '1:514661727749:ios:420a1ad6cd29db0796a66c',
    messagingSenderId: '514661727749',
    projectId: 'mainframe-warfare',
    storageBucket: 'mainframe-warfare.appspot.com',
    iosBundleId: 'thanh.ttm.mwProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7QcQtHacfflLRNQGxFVSu4LPtnfmrkB0',
    appId: '1:514661727749:ios:a2335f46abce363496a66c',
    messagingSenderId: '514661727749',
    projectId: 'mainframe-warfare',
    storageBucket: 'mainframe-warfare.appspot.com',
    iosBundleId: 'thanh.ttm.mwProject.RunnerTests',
  );
}
